### ISSUE TITLE
what is PriorDiscriminator and GlobalDiscriminator?

### ISSUE THREAD

**Issue by A-Rain** [fanyun-sun/InfoGraph#1]
I'm curious about the utility of PriorDiscriminator and GlobalDiscriminator, it seems that in your default parameter setting the code set prior=False and does not use PriorDiscriminator to cacluate part of the loss

**Comment by sunfanyunn** [comment]
I have removed GlobalDiscriminator. They are both experimental codes that are eventually not used nor mentioned in our paper.
If you are really curious about them, check out https://github.com/rdevon/DIM
