### ISSUE TITLE
If I don't have data.y?

### ISSUE THREAD

**Issue by PeterDeSOM** [fanyun-sun/InfoGraph#13]
In the page https://github.com/sunfanyunn/InfoGraph/blob/master/unsupervised/gin.py

I don't have any labeled data.y, so how to learn? Is this unsupervised learning? 
I'm finding a fully unsupervised graph-level clustering/classification method.

If data.y should be needed to train, how many graph-level data have to have its label?
I have millions of graph data that cannot be labeled by human efforts.

**Comment by sunfanyunn** [comment]
duplicate #11
