### ISSUE TITLE
Problem when ran the Reddit-BINARRY dataset.

### ISSUE THREAD

**Issue by ha-lins** [fanyun-sun/InfoGraph#6]
Hi @fanyun-sun,

Thanks for your nice work and released code first!

When I ran the code on the Reddit-BINARY dataset, I got the problem as follows:
![image](https://user-images.githubusercontent.com/22448743/93852807-43988200-fce5-11ea-8935-cc63f5185983.png)

Could you pls help me with the bug? Thanks in advance!

**Comment by carrotYQ** [comment]
Hello, I also meet the same problem like you. Have you solved it? Thanks for sharing~

**Comment by ZsZsZs25** [comment]
> Hi @fanyun-sun,
> 
> Thanks for your nice work and released code first!
> 
> When I ran the code on the Reddit-BINARY dataset, I got the problem as follows: ![image](https://user-images.githubusercontent.com/22448743/93852807-43988200-fce5-11ea-8935-cc63f5185983.png)
> 
> Could you pls help me with the bug? Thanks in advance!

Hello，I got the same problem. Have you solved it?

**Comment by ZzyChris97** [comment]
> > Hi @fanyun-sun,
> > Thanks for your nice work and released code first!
> > When I ran the code on the Reddit-BINARY dataset, I got the problem as follows: ![image](https://user-images.githubusercontent.com/22448743/93852807-43988200-fce5-11ea-8935-cc63f5185983.png)
> > Could you pls help me with the bug? Thanks in advance!
> 
> Hello，I got the same problem. Have you solved it?

I got the same problem have you sloved it ?

**Comment by TalentedMUSE** [comment]
I got the sane problem. Has anybody solved it?
