### ISSUE TITLE
Gap between the performance reported and that of this repo on QM9.

### ISSUE THREAD

**Issue by hengruizhang98** [fanyun-sun/InfoGraph#8]
Hi, we notice that there is a gap between the performance on the QM9 dataset reported and that we reproduced using your code.
e.g. for HOMO(2), the reported RMSE is 0.0060, while with your code it's 0.1560.

**Comment by fanyun-sun** [comment]
Have you trained it for 500 epochs?

**Comment by sunfanyunn** [comment]
I conducted those experiments for the paper in 2019 and the version for `pytorch-geometric==1.3.0` at the time (even though I later tested the code in this repo with `pytorch-geometric==1.6.0`)
Apparently the code and source of QM9 dataset have been changed.
Refer to 
- https://pytorch-geometric.readthedocs.io/en/1.3.0/_modules/torch_geometric/datasets/qm9.html
- https://pytorch-geometric.readthedocs.io/en/1.6.1/_modules/torch_geometric/datasets/qm9.html#QM9

**Comment by sunfanyunn** [comment]
consider the performance reported by this paper in 2019: https://rlgm.github.io/papers/31.pdf

**Comment by hengruizhang98** [comment]
Got it, thank you very much!
